language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

services:
  - mysql

env:
  global:
    - DB_ROOT="root"
    - DB_HOST="127.0.0.1"
    - DB_NAME="beaucallt"
    - DB_USER="beaucallt"
    - DB_PASS="beaucallt"

before_script:
 - mysql -u $DB_ROOT -e "CREATE DATABASE $DB_NAME;" || aborterror "Unable to create database."
 - mysql -u $DB_ROOT $DB_NAME < data/beaucal_throttle.sql || aborterror "Unable to import table."
 - mysql -u $DB_ROOT -e "GRANT ALL ON *.* TO '$DB_USER'@'$DB_HOST' IDENTIFIED BY '$DB_PASS';"
 - composer install

notifications:
  email: false
