language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

services:
  - mysql

env:
  global:
    - DB_HOST="127.0.0.1"
    - DB_NAME="beaucallt"
    - DB_USER="travis"
    - DB_PASS=""

before_script:
 - chmod +x tests/install-apcu.sh
 - tests/install-apcu.sh
 - phpenv config-add tests/apc.ini
 - mysql -uroot -e "CREATE DATABASE $DB_NAME;" || aborterror "Unable to create database."
 - mysql -uroot $DB_NAME < data/beaucal_throttle.sql || aborterror "Unable to import table."
 - mysql -uroot -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'$DB_HOST';"
 - composer install

notifications:
  email: false
